// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJc2feoXCtdePRHwen-9AoniMJSBlyvA',
    appId: '1:49101765732:web:7ce660ff04cd06e4f0b371',
    messagingSenderId: '49101765732',
    projectId: 'testing-af0c0',
    authDomain: 'testing-af0c0.firebaseapp.com',
    databaseURL: 'https://testing-af0c0-default-rtdb.firebaseio.com',
    storageBucket: 'testing-af0c0.appspot.com',
    measurementId: 'G-PGRSLG7FQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRqAcRZKAu9ZgKAcr-MO0aTy3E4UDssY',
    appId: '1:49101765732:android:922f734af84273e4f0b371',
    messagingSenderId: '49101765732',
    projectId: 'testing-af0c0',
    databaseURL: 'https://testing-af0c0-default-rtdb.firebaseio.com',
    storageBucket: 'testing-af0c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnErQs0dJePMWlsRsZbCRAuGPqzc_DT9A',
    appId: '1:49101765732:ios:02683c175bb36679f0b371',
    messagingSenderId: '49101765732',
    projectId: 'testing-af0c0',
    databaseURL: 'https://testing-af0c0-default-rtdb.firebaseio.com',
    storageBucket: 'testing-af0c0.appspot.com',
    iosBundleId: 'com.example.testDaftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnErQs0dJePMWlsRsZbCRAuGPqzc_DT9A',
    appId: '1:49101765732:ios:02683c175bb36679f0b371',
    messagingSenderId: '49101765732',
    projectId: 'testing-af0c0',
    databaseURL: 'https://testing-af0c0-default-rtdb.firebaseio.com',
    storageBucket: 'testing-af0c0.appspot.com',
    iosBundleId: 'com.example.testDaftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaJc2feoXCtdePRHwen-9AoniMJSBlyvA',
    appId: '1:49101765732:web:80533a1cfa544d60f0b371',
    messagingSenderId: '49101765732',
    projectId: 'testing-af0c0',
    authDomain: 'testing-af0c0.firebaseapp.com',
    databaseURL: 'https://testing-af0c0-default-rtdb.firebaseio.com',
    storageBucket: 'testing-af0c0.appspot.com',
    measurementId: 'G-XFR64SGK3W',
  );
}
